import Head from "next/head";
import { useRef } from "react";

import Collaboration from "../components/Collaboration";
import Dashboard from "../components/Dashboard";
import Header from "../components/Header";
import Intro from "../components/Intro";
import Project from "../components/Project";
import ProjectAcceptance from "../components/ProjectAcceptance";
import RoadMap from "../components/RoadMap";
import Technologies from "../components/Technologies";
import Testimonials from "../components/Testimonials";
import styles from "../styles/Home.module.css";
import LottieHeader from "../components/LottieHeader";

export default function Home() {
  const projectRef = useRef(null);
  const roadmapRef = useRef(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotmies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        {/*<Testimonials/>*/}
        <Header projectRef={projectRef} roadmapRef={roadmapRef} />
        <Intro />
        <Project projectRef={projectRef} />
        <Dashboard />
        <Collaboration />
        <Technologies />
        <RoadMap roadmapRef={roadmapRef} />
        <ProjectAcceptance />
        <Testimonials />
      </main>
    </div>
  );
}
